spring:
  application:
    name: voting
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    open-in-view: true
  datasource:
    url: ${DB_URL:}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
server:
  servlet:
    session:
      timeout: 30m
  port: ${SERVER_PORT:8080}
oauth:
  client-id: ${CLIENT_ID:}
  client-secret: ${CLIENT_SECRET:}
image-location: ${IMAGE_LOCATION:}
voting-deadline: ${VOTING_DDL:2024-06-12T12:30:00}
votes-visible-until: ${VOTING_VISIBLE_DDL:2024-06-09T12:30:00}