services:
  db:
    image: mysql:8.0
    volumes:
      - ${MYSQL_MOUNT}:/var/lib/mysql
    restart: always
    env_file:
      - .env
    environment:
      TZ: Asia/Shanghai
      MYSQL_DATABASE: voting
    ports:
      - "3306:3306"
    command:
      --authentication_policy=mysql_native_password
      --character-set-server=utf8mb4
    networks:
      - internal

  app:
    image: voting
    volumes:
      - ${IMAGE_LOCATION}:/var/images
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    env_file:
      - .env
    environment:
      DB_URL: jdbc:mysql://db:3306/voting?useSSL=false&autoReconnect=true&characterEncoding=utf8
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      IMAGE_LOCATION: /var/images
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - internal
    depends_on:
      - db

networks:
  internal: