name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn -B -DskipTests package --file pom.xml
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packaged-jar
          path: target/*.jar